services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/app/credentials/neemble-eat-db-c49af78976aa.json
    volumes:
      - ./app/credentials/neemble-eat-db-c49af78976aa.json:/usr/src/app/app/credentials/neemble-eat-db-c49af78976aa.json:ro