services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/app/credentials/credentials.json
    volumes:
      - ./app/credentials/credentials.json:/usr/src/app/app/credentials/credentials.json:ro